"""unique_hospital_patient_uiid

Revision ID: c27a88d7e851
Revises: 77b7d451b454
Create Date: 2025-12-27 02:20:56.729424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c27a88d7e851'
down_revision: Union[str, Sequence[str], None] = '77b7d451b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('files',
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('visit_id', sa.String(length=36), nullable=True),
    # sa.Column('file_type', sa.String(length=50), nullable=False),
    # sa.Column('file_path', sa.String(length=255), nullable=False),
    # sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # op.drop_table('medical_files')
    # op.drop_table('hospitals')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    # op.drop_column('audit_logs', 'hospital_id')
    # op.drop_column('audit_logs', 'entity_id')
    op.alter_column('bills', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('bills', 'generated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bills', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_bill_status'), table_name='bills')
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.drop_constraint(op.f('bills_ibfk_2'), 'bills', type_='foreignkey')
    # op.drop_column('bills', 'sync_status')
    # op.drop_column('bills', 'hospital_id')
    op.alter_column('patients', 'patient_uiid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("'2000-01-01'"))
    op.alter_column('patients', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_patient_name'), table_name='patients')
    op.create_index(op.f('ix_patients_hospital_id'), 'patients', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_patient_uiid'), 'patients', ['patient_uiid'], unique=False)
    op.create_unique_constraint('uq_hospital_patient_uiid', 'patients', ['hospital_id', 'patient_uiid'])
    # op.drop_constraint(op.f('patients_ibfk_1'), 'patients', type_='foreignkey')
    # op.drop_column('patients', 'age')
    # op.drop_column('patients', 'contact_number')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'staff'"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    # op.drop_column('users', 'updated_at')
    # op.drop_column('users', 'created_at')
    op.alter_column('visits', 'doctor_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('visits', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('visits', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_visit_date'), table_name='visits')
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    # op.drop_constraint(op.f('visits_ibfk_1'), 'visits', type_='foreignkey')
    # op.drop_constraint(op.f('visits_ibfk_2'), 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'patients', ['patient_id'], ['id'])
    # op.drop_column('visits', 'symptoms')
    # op.drop_column('visits', 'notes')
    # op.drop_column('visits', 'prescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('prescription', mysql.TEXT(), nullable=True))
    op.add_column('visits', sa.Column('notes', mysql.TEXT(), nullable=True))
    op.add_column('visits', sa.Column('symptoms', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('visits_ibfk_2'), 'visits', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('visits_ibfk_1'), 'visits', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.create_index(op.f('idx_visit_date'), 'visits', ['visit_date'], unique=False)
    op.alter_column('visits', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('visits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('visits', 'doctor_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'staff'"))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('patients', sa.Column('contact_number', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('patients', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('patients_ibfk_1'), 'patients', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_hospital_patient_uiid', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_patient_uiid'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_hospital_id'), table_name='patients')
    op.create_index(op.f('idx_patient_name'), 'patients', ['name'], unique=False)
    op.alter_column('patients', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'phone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text("'2000-01-01'"))
    op.alter_column('patients', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('patients', 'patient_uiid',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('bills', sa.Column('hospital_id', mysql.VARCHAR(length=36), nullable=False))
    op.add_column('bills', sa.Column('sync_status', mysql.VARCHAR(length=20), server_default=sa.text("'synced'"), nullable=True))
    op.create_foreign_key(op.f('bills_ibfk_2'), 'bills', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.create_index(op.f('idx_bill_status'), 'bills', ['status'], unique=False)
    op.alter_column('bills', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('bills', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bills', 'amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('entity_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('hospital_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('hospitals',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setup_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('medical_files',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('hospital_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('visit_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('patient_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_files_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('medical_files_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
